// Generated by CoffeeScript 1.6.3
(function() {
  var http;

  http = require('http');

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('Hello World\n');
  }).listen(3001, '127.0.0.1');

  console.log('Server running at 127.0.0.1:3001');

}).call(this);
